### ISSUE TITLE
Error: wk does not support sync XHR

### ISSUE THREAD

**Issue by OlafJoppe** [rcha103/MxAutoLogin#1]
I use this plugin succesfully accross several types of windows and android machines. However on apple devices the plugin is causing issues.

I have an app where user accounts are automatically generated by the system. Endusers are supplied with an activation code with which they can redeem the account. When they do they, I automatically log them in with the help of the plugin, implementeed as per the documentation.

This works fine in windows and android, but on iPads and iPhones, the plugin issues error "Error while evaluating javascript input: Error: wk does not support sync XHR."

I have verified the documentation of the xmlhttprequest library and found that all javascript events used by the plugin are in fact supported by Safari, so I am at a loss where the issue might come from and how to prevent it.

**Comment by tmisker** [comment]
Any news on this?
I am having the same issue.

**Comment by tmisker** [comment]
I made the call async and added a handler.
`var xhr = new XMLHttpRequest();
var url = mx.appUrl + "autologin/";
var params = "loginToken=${loginToken}";
xhr.open("POST",url,true);
xhr.setRequestHeader("Content-Type","application/x-www-form-urlencoded; charset=UTF-8");
xhr.onload = function (e) {
  if (xhr.readyState === 4) {
    if (xhr.status === 200) {
      location.reload();
    }
  }
};
xhr.send(params);`

**Comment by rcha103** [comment]
hello @OlafJoppe @tmisker , sorry but I am no longer actively developing using mendix, therefore I cannot maintain any of my community work. You are welcome to fork this and create your own version. Cheers!
